In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Titanic dataset.csv")

In [5]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [3]:
# Filtering passengers who are adults (Age >= 18) and Fare > 30
filtered_df = df[(df["Age"] >= 18) & (df['Fare'] > 30)]

In [4]:
filtered_df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
6,7,54.0,51.8625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
13,14,39.0,31.2750,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
23,24,28.0,35.5000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1291,1292,30.0,164.8667,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1293,1294,22.0,59.4000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1298,1299,50.0,211.5000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1302,1303,37.0,90.0000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,1.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0

In [6]:
# Creating new features
df["Family_Size"] = df['sibsp'] + df['Parch'] + 1
df["Fare_Per_Person"] = df['Fare']/df['Family_Size']

In [7]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived,Family_Size,Fare_Per_Person
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,3,0,0,2.0,0,0,0,2,3.625000
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,1,0,0,0.0,0,0,1,2,35.641650
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,3,0,0,2.0,0,0,1,1,7.925000
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,1,0,0,2.0,0,0,1,2,26.550000
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,3,0,0,2.0,0,0,0,1,8.050000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,3,0,0,2.0,0,0,0,1,8.050000
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,1,0,0,0.0,0,0,0,1,108.900000
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,3,0,0,2.0,0,0,0,1,7.250000
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,3,0,0,2.0,0,0,0,1,8.050000
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,3,0,0,0.0,0,0,0,3,7.452767

In [9]:
df[["Family_Size","Fare_Per_Person"]].head()

   Family_Size  Fare_Per_Person
0            2          3.62500
1            2         35.64165
2            1          7.92500
3            2         26.55000
4            1          8.05000

In [11]:
# Average fare based on passenger class and gender
Avg_fare = df.groupby(["Pclass","Sex"])["Fare"].mean()
Avg_fare

Pclass  Sex
1       0       69.888385
        1      109.412385
2       0       19.904946
        1       23.234827
3       0       12.419597
        1       15.324250
Name: Fare, dtype: float64

In [12]:
df.rename(columns={'2urvived': 'Survived'}, inplace=True)

In [15]:
print(df.columns)

Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', 'Survived', 'Family_Size', 'Fare_Per_Person'],
      dtype='str')

In [ ]:
# Survival rate based on passenger class and gender
survival_rate = df.groupby(['Pclass', 'Sex'])['Survived'].mean() * 100